apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      annotations:
        appVersion: "v1.0.{{ .Timestamp }}"
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z db 5432; do echo waiting for db; sleep 2; done']
      containers:
      - name: myapp
        image: spookeyy/go-todo-backend:latest
        ports:
          - containerPort: 8080
        env:
          - name: DB_HOST
            value: "db"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "todoadmin"
          - name: DB_PASSWORD
            value: "password"
          - name: DB_NAME
            value: "todos"
          - name: DB_URL
            value: "postgresql://todoadmin:password@db:5432/todos?sslmode=disable"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
# service to allow us to access the pods
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 8080
    targetPort: 8080
